import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import midtransRouter from "./midtrans";
import shippingRouter from "./shipping";
import storageRouter from "./storage";
import messagesRouter from "./messages";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import dashboardRouter from "./dashboard";
import supportRouter from "./support";
import wishlistRouter from "./wishlist";
import vouchersRouter from "./vouchers";
import liveRouter from "./live";
import moderationRouter from "./moderation";
import operatorRouter from "./operator";
import billsRouter from "./bills";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(midtransRouter);
router.use(shippingRouter);
router.use(storageRouter);
router.use(messagesRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(dashboardRouter);
router.use(supportRouter);
router.use(wishlistRouter);
router.use(vouchersRouter);
router.use(liveRouter);
router.use(moderationRouter);
router.use(operatorRouter);
router.use(billsRouter);

export default router;
